# Called with: sudo ansible-playbook install_developer_tools.yaml --ask-become-pass"
- hosts: localhost
  become: yes
  tasks:

  - name: Get $HOME variable
    shell: "echo $HOME"
    become: no
    register: HOME

  - name: Get $USER variable
    shell: echo $USER
    become: no
    register: USER

  - name: Configure aliases
    ansible.builtin.copy:
      src: "{{playbook_dir}}/cfg/bash/.bash_aliases"
      dest: "{{HOME.stdout_lines[0]}}/"

  - name: Appending data to bashrc
    shell: "cat {{playbook_dir}}/cfg/bash/.bashrc >> ~/.bashrc"
    become: no

  - name: Install terminator
    apt:
      name: terminator

  - name: Install htop
    apt:
      name: htop

  - name: Install tree
    apt:
      name: tree

  - name: Configure terminator
    ansible.builtin.copy:
      src: "{{playbook_dir}}/cfg/terminator/config"
      dest: "{{HOME.stdout_lines[0]}}/.config/terminator/"

  - name: Install fonts
    ansible.builtin.copy:
      src: "{{playbook_dir}}/cfg/NerdFonts"
      dest: "{{HOME.stdout_lines[0]}}/.local/share/fonts"

  - name: Clone FZF
    ansible.builtin.git:
      repo: "https://github.com/junegunn/fzf.git"
      dest: "{{playbook_dir}}/fzf"

  - name: Installation FZF
    shell: "sudo -E {{playbook_dir}}/fzf/install --key-bindings --completion --update-rc"
    become: no

  - name: Clone FZF marks
    ansible.builtin.git:
      repo: 'https://github.com/urbainvaes/fzf-marks.git'
      dest: "{{playbook_dir}}/fzf-marks"

  - name: Source FZF marks
    shell: echo "source {{playbook_dir}}/fzf-marks/fzf-marks.plugin.bash" >> ~/.bashrc
    become: no

  - name: Setting up git alias for checkout
    shell: git config --global alias.co checkout
    become: no

  - name: Setting up git alias for branch
    shell: git config --global alias.br branch
    become: no

  - name: Setting up git alias for status
    shell: git config --global alias.st status
    become: no

  - name: Setting up git alias for commit
    shell: git config --global alias.ci commit
    become: no

  - name: Install chrome and set up extensions
    shell: bash {{playbook_dir}}/scripts/setup_chrome.sh
    # Side note: blank.org is my home page, set up in the "redirect tab" plugin
