# Called with: sudo ansible-playbook install_developer_tools.yaml --ask-become-pass"
- hosts: localhost
  become: yes
  tasks:

  - name: Get $HOME variable
    shell: "echo $HOME"
    become: no
    register: HOME

  - name: Install terminator
    apt:
      name: terminator

  - name: Configure terminator
    ansible.builtin.copy:
      src: "{{playbook_dir}}/cfg/terminator/config"
      dest: "{{HOME.stdout_lines[0]}}/.config/terminator/"

  - name: Install Nerd Font
    ansible.builtin.git:
      repo: "https://aur.archlinux.org/nerd-fonts-hack.git"
      dest: "{{HOME.stdout_lines[0]}}/.fonts"

  - name: Clone FZF
    ansible.builtin.git:
      repo: "https://github.com/junegunn/fzf.git"
      dest: "{{playbook_dir}}/fzf"

  - name: Install FZF
    shell: "{{playbook_dir}}/fzf/install"
    become: no


  - name: Clone FZF marks
    ansible.builtin.git:
      repo: 'https://github.com/urbainvaes/fzf-marks.git'
      dest: "{{playbook_dir}}/fzf-marks"

  - name: Source FZF marks
    shell: echo "source {{playbook_dir}}/fzf-marks/fzf-marks.plugin.bash" >> ~/.bashrc
    become: no
