# Ranger
# Terminator
- hosts: localhost
  become: no
  tasks:

  - name: Get $HOME variable
    shell: "echo $HOME"
    become: no
    register: HOME

  - name: Update ranger config from the laptop to the repo
    ansible.builtin.copy:
      src: "{{HOME.stdout_lines[0]}}/.config/ranger/rc.conf"
      dest: "{{HOME.stdout_lines[0]}}/mflova-linux-setup/developer/cfg/ranger/"

  - name: Update ranger commands from the laptop to the repo
    ansible.builtin.copy:
      src: "{{HOME.stdout_lines[0]}}/.config/ranger/commands.py"
      dest: "{{HOME.stdout_lines[0]}}/mflova-linux-setup/developer/cfg/ranger/"

  - name: Update terminator config
    ansible.builtin.copy:
      src: "{{HOME.stdout_lines[0]}}/.config/terminator/config"
      dest: "{{HOME.stdout_lines[0]}}/mflova-linux-setup/developer/cfg/terminator/config"
    become: no
