- name: Install full I3
  import_playbook: "{{playbook_dir}}/../developer/install_developer_tools.yaml"

- name: Install full I3
  import_playbook: "{{playbook_dir}}/../mfova-i3-setup/playbooks/full_installation.yaml"
